[package]
name = "yarge"
version = "0.1.0"
authors = ["xshifty"]
edition = "2018"

[dependencies.sdl2]
version = "0.32.2"
default-features = false
features = ["image", "ttf"]

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"
